# Generated by Django 6.0.7 on 2026-08-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service_interested',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
