# Generated by Django 6.0.7 on 2026-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='short_intro',
            field=models.TextField(blank=True, help_text='Short text for the Hero section', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, help_text='Detailed text for the About section', null=True),
        ),
    ]
