# Generated by Django 6.0.7 on 2026-08-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userprofile_short_intro_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='services_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Services section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='services_title',
            field=models.CharField(default='My Services', max_length=200),
        ),
    ]
