# Generated by Django 6.0.7 on 2026-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_userprofile_services_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highlights_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Highlights section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highlights_title',
            field=models.CharField(default='Project Highlights', max_length=200),
        ),
    ]
