# Generated by Django 6.0.7 on 2026-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_projectcategory_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(default='', help_text="Enter categories separated by commas (e.g. 'React, UI/UX, Mobile App')", max_length=255),
            preserve_default=False,
        ),
    ]
