# Generated by Django 6.0.7 on 2026-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_categories_delete_projectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='works_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Works section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='works_title',
            field=models.CharField(default='Selected Works', max_length=200),
        ),
    ]
