# Generated by Django 6.0.7 on 2026-08-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_userprofile_works_subtitle_userprofile_works_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='works_title',
            field=models.CharField(default='Selected Projects', max_length=200),
        ),
    ]
