# Generated by Django 6.0.7 on 2026-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_userprofile_works_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='highlights/')),
                ('row_number', models.IntegerField(default=1, help_text='Which row should this image appear in? (1 or 2)')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['row_number', 'display_order', '-created_at'],
            },
        ),
    ]
