# Generated by Django 6.0.7 on 2026-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_projecthighlight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectHighlight',
        ),
        migrations.AddField(
            model_name='project',
            name='highlight_row',
            field=models.IntegerField(choices=[(0, 'Do Not Highlight'), (1, 'Highlight in Row 1'), (2, 'Highlight in Row 2')], default=0, help_text="Select a row to feature this project's thumbnail in the Highlights section."),
        ),
    ]
