# Generated by Django 6.0.7 on 2026-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_delete_projecthighlight_project_highlight_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Layers', help_text='Name of the Lucide React icon (e.g., Search, Layers, Server, Code, Activity)', max_length=100)),
                ('step_number', models.CharField(help_text='Step number (e.g., 01, 02)', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='process_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Process section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='process_title',
            field=models.CharField(default='My Development Process', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tools_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Tools section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tools_title',
            field=models.CharField(default='Tools I Work With', max_length=200),
        ),
    ]
