# Generated by Django 6.0.7 on 2026-08-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_processstep_userprofile_process_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='step_number',
        ),
    ]
