# Generated by Django 6.0.7 on 2026-08-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_processstep_step_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='cv_file',
        ),
    ]
