# Generated by Django 6.0.7 on 2026-08-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_education_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='highlight_color',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='short_description',
        ),
    ]
