# Generated by Django 6.0.7 on 2026-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_experience_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Short tagline for Hero section', max_length=255, null=True),
        ),
    ]
