# Generated by Django 6.0.7 on 2026-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_userprofile_hero_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_description',
            field=models.TextField(blank=True, help_text='Description for the Contact section card', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_heading',
            field=models.CharField(default="Let's create something extraordinary", max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for the Contact section', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_title',
            field=models.CharField(default='Get In Touch', max_length=200),
        ),
    ]
